- name: start services lb
  hosts: lb
  tasks:
  - name: stop soft
    ansible.builtin.command: "nginx -s stop && pkill -f keepalived"
  - name: check ps
    ansible.builtin.command: "ps aux"

  - name: start keepalived
    ansible.builtin.command: "keepalived -f /etc/keepalived/keepalived.conf &"

  - name: Wait 5 seconds for keepalived VIP
    ansible.builtin.pause:
      seconds: 5

  - name: Start nginx
    ansible.builtin.command: "nginx"
